# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6aba3c1ac8591ca25f5d5cbc1502118e4a3cda235525b3274cf70e904433bafaed25dad35bc12a5da44661a4abb484622bd0dc94b0ad71d4a8c46118c42c9a4a

test:
  secret_key_base: e34a498b6a45c471af0f4b730399012571b2c7ae7669fc9c94df693a47190d0745c92cb495c117ee53c9b1c838fb2b2ddd1cf85c2a4ccfd1f53e926c6a7999f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
